version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: goodnight_app
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: goodnight_app_development
    volumes:
      - store:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: goodnight_app_api
    command: ./bin/rails server -b 0.0.0.0
    links:
      - db
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://goodnight_app:examplepassword@db:5432/goodnight_app_development
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  store:
    driver: local
  bundle:
    driver: local